### ISSUE TITLE
Option to highlight only after only double click

### ISSUE THREAD

**Issue by Opioid** [fgeller/highlight-thing.el#10]
By default all occurrences of the thing under the cursor get highlighted. This can be distracting while typing, especially since the default highlight color is almost the same as the cursor.
Is it possible to add an option so that only things selected with a double click get highlighted (similar to what sublime text does)?

**Comment by fgeller** [comment]
hi @Opioid - sorry that i missed the notification for this issue.

you can modify the color that highlight-thing uses by customizing the face `highlight-thing`. for example via `M-x customize-face RET highlight-thing RET`.

i use emacs in a terminal so i wouldn't get double click feedback. but from what i read you can rebind the mouse events: https://www.gnu.org/software/emacs/manual/html_node/emacs/Mouse-Buttons.html

so to do this globally you could try something like this (quick disclaimer as i haven't tested this):

```
 (defun highlight-thing-double-click ()
   (interactive)
   (highlight-thing-do))

 (global-set-key [double-mouse-1] 'highlight-thing-double-click)
```

which should allow you to trigger the highlighting through a double click. (you can also use a regular shortcut there). and simply don't start the minor mode to disable the automatic highlighting.

please feel free to ping me here again and re-open the ticket if that doesn't work for you :)

**Comment by Opioid** [comment]
Thanks for the reply. Currently I'm using highlight-symbol which works well for me.
