### ISSUE TITLE
Highlight everything like the thing at point but not the thing at point

### ISSUE THREAD

**Issue by Kaligule** [fgeller/highlight-thing.el#11]
It would be nice to have an option to highlight all the matches, but not the one occurence that is at point itself.

**Comment by fgeller** [comment]
cool feedback - thanks!

try updating and `(setq highlight-thing-exclude-thing-under-point t)` (or equivalent) and re-open or ping me here if something doesn't work!

**Comment by Kaligule** [comment]
I am a bit irritated about how fast you are.
Works perfectly for me, thanks a lot.
I will sent a pullreqest to update the documentation.

**Comment by fgeller** [comment]
that's a good irritated then - right? ;)

cool, had that readme on my list for today, thanks a lot!
