### ISSUE TITLE
Ignore list

### ISSUE THREAD

**Issue by humitos** [fgeller/highlight-thing.el#13]
Hi,

I've being using `highlight-symbol` and I found this one today and I liked it more because it has some configurations that the other one doesn't have.

The only thing that this one is missing, I think, it's the ability to add symbols to an ignore list and don't highlight them. I found this very useful because otherwise I feel like it's too intrusive.

For example, my list it's similar to this (for Python code):

```lisp
(setq highlight-symbol-ignore-list
      '("False" "True" "None" "self" "def" "import" "from" "if" "else" "for" "while" "class" "print" "and" "not" "is" "param" "type" "rtype" "async"))
```

That's all, thank you for this code! :)

**Comment by fgeller** [comment]
Hi @humitos - thanks for the feedback!

Sounds good to me - are you interested in providing a PR for it? If not I think I should be able to get around to it today or tomorrow?

**Comment by fgeller** [comment]
Hi @humitos - took a bit longer, but hope the above helps. To use it:

```emacs-lisp
(setq highlight-thing-ignore-list '("False" "True" "None" "self" "def" "import" "from" "if" "else" "for" "while" "class" "print" "and" "not" "is" "param" "type" "rtype" "async"))
```

Let me know if that doesn't work for you!
