### ISSUE TITLE
README outdated

### ISSUE THREAD

**Issue by humitos** [fgeller/highlight-thing.el#14]
Not really sure, but it seems that `highlight-symbol.el` requires `thingatpt` only to work properly.

**Comment by fgeller** [comment]
Hi @humitos, do you mean that it doesn't require `hi-lock` anymore? The dependency on `hi-lock` isn't as explicit as the dependency on `thingatpt`, which is a `(require 'thingatpt)`: at its core, `highlight-thing.el` uses the function `highlight-regexp` and some other functionality from `hi-lock` that you can find if you search for the `hi-` prefix. Does that address the issue?

**Comment by fgeller** [comment]
closing this for now, feel free to re-open if you could get back to me about the above
