### ISSUE TITLE
highlight region if any, highlight default thing otherwise

### ISSUE THREAD

**Issue by ahlearn** [fgeller/highlight-thing.el#15]
Is it possible to have following behavior?
if there is an active region, then act like (setq highlight-thing-what-thing 'region)
otherwise, act like (setq highlight-thing-what-thing 'word)

**Comment by fgeller** [comment]
thanks for the feedback @ahlearn -- added the above. 

```emacs-lisp
```

**Comment by ahlearn** [comment]
Thank you! :)
