### ISSUE TITLE
Add an option to highlight-in-all-visible-buffers

### ISSUE THREAD

**Issue by ahlearn** [fgeller/highlight-thing.el#17]
Related background https://stackoverflow.com/questions/15415504/highlighting-multiple-buffers-in-emacs

**Comment by AlexYegupov** [comment]
yes, this missing ability to keep highlighting the passive frame.
highlight-thing-prefer-active-region doesnt' help

**Comment by fgeller** [comment]
hey all - thanks for the interesting request! :+1:  I added an option to highlight in all visible buffers in the current frame. I don't really use multiple emacs frames (actually i use it only inside a terminal), but adding it shouldn't be too difficult if i could get a volunteer for testing? in any case, i added a note to the readme, let me know if you run into any issues!

**Comment by AlexYegupov** [comment]
Big thanks for coding but seems doesn't work: I'm opening two different files on different frames and looks like highlighting disappearing after frame deactivating (green underline):
https://www.useloom.com/share/51e3197b0f5f4c6b87b22b8561ab8e4d

emacs settings:

(require 'highlight-thing)


(add-hook 'js-mode-hook 'highlight-thing-mode)
(add-hook 'text-mode-hook 'highlight-thing-mode)

**Comment by fgeller** [comment]
hi @AlexYegupov - thanks for the feedback! i just added a bit that enables highlighting across frames, let me know if you run into any issues!
