### ISSUE TITLE
Failed to change highlight-thing face

### ISSUE THREAD

**Issue by ianpan870102** [fgeller/highlight-thing.el#19]
First of all, thanks for making this package -- I really love it!
However, when I tried to change the highlight face with `(set-face-attribute 'highlight-thing nil :foreground "white")`, Emacs tellls me `Invalid face: highlight-thing`. How should I approach this?

**Comment by ianpan870102** [comment]
P.s. using `set-face-foreground` or `set-face-background` yields the same result.

**Comment by d1egoaz** [comment]
@ianpan870102 this works for me:
```elisp
(custom-set-faces
   '(highlight-thing ((t (:background "yellow" :foreground "black")))))
```

**Comment by fgeller** [comment]
@ianpan870102 thanks, i'm glad you enjoy the package!

from the docs, it sounds like `set-face-attribute` is meant for internal use mostly, have you tried @d1egoaz 's version using `custom-set-faces` or found another solution?

@d1egoaz thanks for offering help!

**Comment by fgeller** [comment]
i'll close this for now, please re-open if there's a way i can help!
