### ISSUE TITLE
Feature request: highlight only occurences in current defun

### ISSUE THREAD

**Issue by Fuco1** [fgeller/highlight-thing.el#2]
`thingatpt` has a `defun` method so you can test if point is inside a defun or not.  If so, narrow before applying the highlight (at least, I hope hi-lock can use that).

What do you think?  Often the symbol has no relevance outside the defun.  Of course, you can make this an opt-in feature.

**Comment by fgeller** [comment]
Thanks for your feedback!
Let me know if 75596dd isn't what you were looking for :)

**Comment by Fuco1** [comment]
I added some notes to the commit. Thanks for a quick response!

**Comment by fgeller** [comment]
Thanks again :)

Let me know what you think of the changes!

**Comment by Fuco1** [comment]
Awesome.

One more thing.  You can (and should) also specify the type of the customize option.  This enables emacs to 

a) do verification on the type (if user sets some nonsensical value it will bug them about it rather than silently fail somewhere) 
b) draw the proper UI widget in the customize interface

You can read about that here: https://www.gnu.org/software/emacs/manual/html_node/elisp/Customization-Types.html

Also notice it specifies the `:group` option, that's used to group the options related to one package under the same menu.

**Comment by Fuco1** [comment]
Hm, actually, I tried the new version now and it doesn't seem to limit the highlight to defun.  Does it work for you? (I still use emacs 24.3)

**Comment by Fuco1** [comment]
Ok, figured it out.  It uses font-lock to do the highlight, and that simply works on the entire buffer.  If we disable `font-lock-mode` then it uses overlays and the logic for placing those respects the bounds.

Another weirdity of emacs :D  So I changed the defun to

```emacs
(defun highlight-thing-do ()
  (interactive)
  (let* ((thing (thing-at-point highlight-thing-what-thing))
         (font-lock-mode nil))
    (highlight-thing-remove-last)
    (when (and (highlight-thing-should-highlight) thing)
      (save-excursion
        (save-restriction
          (widen)
          (when highlight-thing-limit-to-defun (narrow-to-defun))
          (highlight-regexp (highlight-thing-regexp thing) 'highlight-thing)))
      (setq highlight-thing-last-buffer (current-buffer))
      (setq highlight-thing-last-thing thing))))
```

In case no narrowing happens, using font lock is probably much better idea as it is way faster than overlays (especially on large buffers).

**Comment by fgeller** [comment]
Took a bit longer this time, but added type and group information to defcustoms in e2f27a6 -- let me know what you think! 
Re font-lock-mode: One of my assumptions for this mode is that font-lock-mode is turned off, so added that part as well to make it explicit. Thanks for looking into it :)

**Comment by Fuco1** [comment]
Sweet, I'll check it out tomorrow, just heading to bed.
