### ISSUE TITLE
Feature request: exclude matches in comment blocks

### ISSUE THREAD

**Issue by hrmcginnis** [fgeller/highlight-thing.el#20]
It would be useful for me if it were possible configure `highlight-thing-mode` to prevent an instance of a symbol from being highlighted if that instance is part of a comment block or code intended for documentation (e.g. if the face is `font-lock-comment-face` or `font-lock-doc-face`).

Thanks for the great work on this minor mode!

**Comment by fgeller** [comment]
@hrmcginnis glad the small minor mode helps!

I currently don't see a straight-forward way of achieving this as we leave the searching and highlighting to Emacs' built-in `highlight-regexp` / `hi-lock-face-buffer`. So we'd have to remove overlays that the built-in added, essentially searching for matches again, unless we implement a custom version of the built-in. I decided to use the built-in for simplicity and speed and prefer to stick to that for now. Maybe you see another way or found a different solution? 

I'll be closing the issue for now but feel free to continue the discussion!
