### ISSUE TITLE
Point moves in ruby when over the `module` keyword

### ISSUE THREAD

**Issue by Fuco1** [fgeller/highlight-thing.el#6]
This is really odd and I can't explain it, here is what I do:

1. make a clean buffer
2. input

    
    module
    
    end

3. place point over `m` in `module`
4. point should spotaneously move forward one character.

I guess there's a missing `save-excursion` somewhere, unfortunately I don't have time to look into it.

**Comment by fgeller** [comment]
I tried to reproduce this in a ruby buffer: `m o d u l e <return> e n d C-a <up>` but point doesn't change for me. I'm testing this on GNU Emacs 24.5.1 (x86_64-apple-darwin14.3.0, NS apple-appkit-1347.57) with the default ruby-mode.

What ruby-mode or other minor modes are you using?

**Comment by Fuco1** [comment]
Hm, okey then, I'll investigate further.  I use some older ruby mode, I'll try to get the latest and see what happens.

**Comment by fgeller** [comment]
Cool, let me know if can help

**Comment by fgeller** [comment]
@Fuco1 I'll close this one for now, feel free to re-open if the problem re-appears :)
