### ISSUE TITLE
Feature request: highlight text like region only

### ISSUE THREAD

**Issue by Kaligule** [fgeller/highlight-thing.el#7]
It would be nice to have things highlighted only if they are selected in the region.

This would mean your eye isn't distracted when doing simple typing, but only when selecting stuff like variables and lines that repeat frewuently. It could also lead to nice synergy effects with other packages like expand-region etc for free.

**Comment by fgeller** [comment]
Thanks for your feedback! Do you mean that things should only be highlighted in an active region? 

e.g., if point is `|` and `@` is mark:

You set mark in a situation like the sample below:

```
abc|
def
abc
def
abc
```

you then move point to 

```
abc@
def
abc
def
abc|
```

and only the second and third `abc` would get highlighted?

```
abc@
def
[abc]
def
[abc]|
```

Or were you thinking of another case?

**Comment by Kaligule** [comment]
No, I actually ment a different thing. In your example (@ is mark, | is point, [] is highlight)

```
abc
def
abc|
def
abc
```
(mark not set, so nothing is highlighted)

```
[abc]
def
@abc|
def
[abc]
```
(mark is set, so everything like the thing between mark and point is highlighted)
Another example:

```
[abc xyz]
def
@abc xyz|
def
abc def 
```
No that I reread my issue, you really could not understand what I meant myself, sorry for this.

**Comment by fgeller** [comment]
Cool idea, let me know if this works for you: `(setq highlight-thing-what-thing region)`

**Comment by Kaligule** [comment]
Works like a charm. Great work. Thank you.
