### ISSUE TITLE
Controlling case sensitivity

### ISSUE THREAD

**Issue by fmarier** [fgeller/highlight-thing.el#8]
I would like highlight-thing to be case-sensitive when in a coding mode.

Here's an example of why it's useful:

![case-insensitive](https://cloud.githubusercontent.com/assets/167821/12210775/4d8b7b52-b611-11e5-9c6e-dbda5b60a352.png)

Because it's not currently case-sensitive, I don't notice that the variable I'm defining (`allowlist`) doesn't match the usage below (`allowList`).

**Comment by fgeller** [comment]
Hi @fmarier --

Sorry for the delay in getting back to you on this. I pushed a change that allows you to change the matching to be case-sensitive by doing the following in your setup:

    (setq highlight-thing-case-sensitive-p t)

Or via `M-x customize-variable highlight-thing-case-sensitive-p`.

Thank you for your feedback and please let me know if you run into any issues! (should be quicker in getting back to you now :))

**Comment by fmarier** [comment]
It works great, thanks!
