### ISSUE TITLE
How do I change the highlight color?

### ISSUE THREAD

**Issue by der-Daniel** [fgeller/highlight-thing.el#9]
I look at the commit, but could not figure it out..
This is what I got:

```
(use-package 
  highlight-thing 
  :ensure t 
  :config (global-highlight-thing-mode))
(defface highlight-thing
   '((t (:inherit 'hi-black-hb))) "")
```

**Comment by fgeller** [comment]
the face is already defined by the minor mode so you could use the following:

```
(use-package
  highlight-thing
  :ensure t
  :config
  (global-highlight-thing-mode)
  (set-face-foreground 'highlight-thing "white")
  (set-face-background 'highlight-thing "green"))
```

or alternatively `(set-face-attribute 'highlight-thing nil :foreground "white")`

hope this helps!

**Comment by fgeller** [comment]
closing the issue, but feel free to continue asking through this issue!
